/*
 * Java bean class for entity table card_tags 
 * Created on 1 May 2017 ( Date ISO 2017-05-01 - Time 07:43:04 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package model.entities;

import java.io.Serializable;


/**
 * Entity bean for table "card_tags"
 * 
 * @author Telosys Tools Generator
 *
 */
public class CardTags implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    id           ; // Primary Key

    private Integer    cardId       ;
    private Integer    tagId        ;

    /**
     * Default constructor
     */
    public CardTags()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "id" field value
     * This field is mapped on the database column "id" ( type "serial", NotNull : true ) 
     * @param id
     */
	public void setId( Integer id )
    {
        this.id = id ;
    }
    /**
     * Get the "id" field value
     * This field is mapped on the database column "id" ( type "serial", NotNull : true ) 
     * @return the field value
     */
	public Integer getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : card_id ( int4 ) 
    /**
     * Set the "cardId" field value
     * This field is mapped on the database column "card_id" ( type "int4", NotNull : true ) 
     * @param cardId
     */
    public void setCardId( Integer cardId )
    {
        this.cardId = cardId;
    }
    /**
     * Get the "cardId" field value
     * This field is mapped on the database column "card_id" ( type "int4", NotNull : true ) 
     * @return the field value
     */
    public Integer getCardId()
    {
        return this.cardId;
    }

    //--- DATABASE MAPPING : tag_id ( int4 ) 
    /**
     * Set the "tagId" field value
     * This field is mapped on the database column "tag_id" ( type "int4", NotNull : true ) 
     * @param tagId
     */
    public void setTagId( Integer tagId )
    {
        this.tagId = tagId;
    }
    /**
     * Get the "tagId" field value
     * This field is mapped on the database column "tag_id" ( type "int4", NotNull : true ) 
     * @return the field value
     */
    public Integer getTagId()
    {
        return this.tagId;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(cardId);
        sb.append("|");
        sb.append(tagId);
        return sb.toString(); 
    } 


}
