/*
 * Java bean class for entity table history 
 * Created on 1 May 2017 ( Date ISO 2017-05-01 - Time 07:43:04 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package model.entities;

import java.io.Serializable;

import java.util.Date;

/**
 * Entity bean for table "history"
 * 
 * @author Telosys Tools Generator
 *
 */
public class History implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    id           ; // Primary Key

    private Integer    cardId       ;
    private Date       reviewedTime ;
    private Integer    nextTime     ;

    /**
     * Default constructor
     */
    public History()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "id" field value
     * This field is mapped on the database column "id" ( type "serial", NotNull : true ) 
     * @param id
     */
	public void setId( Integer id )
    {
        this.id = id ;
    }
    /**
     * Get the "id" field value
     * This field is mapped on the database column "id" ( type "serial", NotNull : true ) 
     * @return the field value
     */
	public Integer getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : card_id ( int4 ) 
    /**
     * Set the "cardId" field value
     * This field is mapped on the database column "card_id" ( type "int4", NotNull : true ) 
     * @param cardId
     */
    public void setCardId( Integer cardId )
    {
        this.cardId = cardId;
    }
    /**
     * Get the "cardId" field value
     * This field is mapped on the database column "card_id" ( type "int4", NotNull : true ) 
     * @return the field value
     */
    public Integer getCardId()
    {
        return this.cardId;
    }

    //--- DATABASE MAPPING : reviewed_time ( timestamp ) 
    /**
     * Set the "reviewedTime" field value
     * This field is mapped on the database column "reviewed_time" ( type "timestamp", NotNull : true ) 
     * @param reviewedTime
     */
    public void setReviewedTime( Date reviewedTime )
    {
        this.reviewedTime = reviewedTime;
    }
    /**
     * Get the "reviewedTime" field value
     * This field is mapped on the database column "reviewed_time" ( type "timestamp", NotNull : true ) 
     * @return the field value
     */
    public Date getReviewedTime()
    {
        return this.reviewedTime;
    }

    //--- DATABASE MAPPING : next_time ( int4 ) 
    /**
     * Set the "nextTime" field value
     * This field is mapped on the database column "next_time" ( type "int4", NotNull : true ) 
     * @param nextTime
     */
    public void setNextTime( Integer nextTime )
    {
        this.nextTime = nextTime;
    }
    /**
     * Get the "nextTime" field value
     * This field is mapped on the database column "next_time" ( type "int4", NotNull : true ) 
     * @return the field value
     */
    public Integer getNextTime()
    {
        return this.nextTime;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(cardId);
        sb.append("|");
        sb.append(reviewedTime);
        sb.append("|");
        sb.append(nextTime);
        return sb.toString(); 
    } 


}
